### PR TITLE
Shrinking image size

### PR DESCRIPTION
**Pull request by sstarcher**
Moved build deps into the /bin/install script
New image size is 188mb

@masneyb
@ajmath 
@rhussmann 
@kelcecil 
@MichaelRBond 
@jdavis92
@alexjpaz 
@brendangibat
@jmmartin

I think that's all of the people who commented on #34.  Could someone test this PR before I merge it.

### CODE REVIEW

**Comment by kelcecil** [comment]
I'll test it tomorrow if someone doesn't beat me to it.

**Comment by sstarcher** [comment]
173.9mb after dropping ruby gem cache/doc

**Comment by masneyb** [comment]
I tested this against our image and ran into an issue. Here is a snippet of our Dockerfile:

    RUN apt-get update && apt-get -y curl # and some other packages
    RUN /bin/install mailer pagerduty
    # Curl is no longer installed after install runs

On line 6 of your existing Dockerfile, you already install curl and leave it in that layer. I suggest dropping curl from the DEBIAN_TOOLING variable in the install script.

Brian

**Comment by sstarcher** [comment]
@masneyb what is using curl?  Are actual plugins during runtime using it?

**Comment by masneyb** [comment]
We use curl in our Dockerfile that is based off your image to install additional dependencies.

You install curl in your first RUN command and later delete it in a different layer at the end of the install command. Removing curl at that point won't actually shrink the image size unless the image layers are squashed.

Brian

**Comment by masneyb** [comment]
Here is an example Dockerfile that is based off your image that illustrates the problem:

    FROM this_branches_image_id_from_docker_build
    RUN apt-get update && apt-get install -y curl
    RUN /bin/install pagerduty
    # Curl is no longer installed after /bin/install runs
    RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"

Brian

**Comment by sstarcher** [comment]
@masneyb I'll keep curl installed.  Try again

**Comment by masneyb** [comment]
:shipit:

**Pull request merged**
