### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by jwarnier**

### CODE REVIEW

**Comment by sstarcher** [comment]
Did something change that is making this not work as is?

**Comment by jwarnier** [comment]
I'm sorry @sstarcher, but I don't understand your question.

**Comment by sstarcher** [comment]
Why do we need this change?  What does it accomplish?  Is something broken?

**Comment by sstarcher** [comment]
Please let me know if you have time to circle back and answer my questions.  I just mainly want to know what issue this is fixing.  We don't want to make changes just to make changes.

**Pull request closed without merging**
